### ISSUE TITLE
Input filename before variables in imports

### ISSUE THREAD

**Issue by Gelio** [xabikos/vscode-javascript#11]
Since VSCode provides useful Intellisense when the filename is provided first in the import statements, I suggest that the focus is first on the filename and then on the variables that we want to import.

This way we get name completion when typings and a list of possible elements to import when pressing Ctrl + Space.

I can make the pull request, if you would like. In fact, I would really like to, as it would be my first open source contribution. Just let me know, because I am not sure if you want to incorporate the change or not.

By the way, this project is great and has saved me a lot of typings, so good job ;)

**Comment by 19majkel94** [comment]
You can use the snippets from [here](/xabikos/vscode-javascript/blob/master/snippets/snippets.json) and use it in your custom vscode snippets. I did this because i use double quotes in import statements.

**Comment by Gelio** [comment]
I know, I just thought it may be a good enhancement and it won't take any
current functionalities away

**Comment by xabikos** [comment]
Hello @Gelio and sorry for my really late reply. Yes please go ahead with the pull request. 
The change shouldn't be hard to implement and feel free to ping me if you face any problem. Once you will do it I will publish a new version that will include the [promise snippet too](https://github.com/xabikos/vscode-javascript/issues/12)

**Comment by Gelio** [comment]
Hi @xabikos, no problem, I've just made the pull request. I'm awaiting your feedback.

Thank you for allowing me to contribute, by the way! You're awesome :smile:
