### ISSUE TITLE
in .tsx file not workings

### ISSUE THREAD

**Issue by chanceyliu** [xabikos/vscode-javascript#112]
I did not make any changes in configuration after installation

in .tsx file
<img width="731" alt="image" src="https://user-images.githubusercontent.com/50861437/217134290-e7a0e35d-6380-4cc4-945e-7fb383eb5bc7.png">

in .ts file
<img width="693" alt="image" src="https://user-images.githubusercontent.com/50861437/217134911-e31e3b71-f3e9-4c9e-b38e-9ac777c75b35.png">

**Comment by kostyabushuev** [comment]
@chanceyliu 
It seems like VSCode bug. Related issue - https://github.com/microsoft/vscode/issues/173244

[Advice to use snippets](https://github.com/microsoft/vscode/issues/173244#issuecomment-1415317898): Try `Ctrl+Space` after having entered the snippet prefix. Or move the text cursor away, then back, and then do `Ctrl+Space`.
