### ISSUE TITLE
Tabs/spaces, semicolons

### ISSUE THREAD

**Issue by wmertens** [xabikos/vscode-javascript#16]
I wonder, is it possible to make the snippets configurable so that the spaces become tabs and the semicolons are left out?

If not, perhaps you could make a second extension for tabs, no semi?

**Comment by xabikos** [comment]
Hello @wmertens and sorry for my late reply. I don't think we can configure the snippets regarding the spaces and the semicolons. At least I can't imagine a way to do that.

Now about the second extension I think it would make the entire snippets functionality more complicated. I know I had to make a choice on how to implement that and it doesn't fit all the tastes but I can't do much about it. Even if I make a different version then someone else could argue that prefer tabs with semicolons. I hope you understand.
