### ISSUE TITLE
Pressing 'imp' causes 'implements' to come out instead.

### ISSUE THREAD

**Issue by ndaljr** [xabikos/vscode-javascript#22]
![image](https://cloud.githubusercontent.com/assets/18214059/22781895/89bb893c-eeff-11e6-9453-b841c4fa3fde.png)

![image](https://cloud.githubusercontent.com/assets/18214059/22781908/9212f87c-eeff-11e6-9acd-79d130f745a3.png)

This particular snippet doesn't seem to work well. Could you help me out?

**Comment by xabikos** [comment]
Sorry for my late reply @ndaljr 
Unfortunately there is nothing to be done. Once you type imp you get a list with suggestions. You need to choose the appropriate entry for that selection. A possible fix would be to add an additional snippet for that like `imrt`

**Comment by b3vegan** [comment]
@ndaljr @xabikos 

I was just looking into this myself and found that you can set your snippets to appear above other suggestions in IntelliSense.

Add this to your settings.json file:

"editor.snippetSuggestions": "top"

Now when you type 'imp', any snippets with that prefix will appear before anything else in the list of suggestions.

Other options for "editor.snippetSuggestions" are "bottom" and "inline" (meaning ordered alphabetically inline with other suggestions), and "none' if you want to remove snippet suggestions completely.

More information here:
https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense

**Comment by xabikos** [comment]
@b3vegan That's an excellent solution. I didn't know about that.

Thank you so much! 

So @ndaljr I guess that this address your issue, right?

**Comment by ndaljr** [comment]
Yes it does. Thank you so much! I'll close this issue. Cheers
