### ISSUE TITLE
 can it support  .vue file ?

### ISSUE THREAD

**Issue by herrdu** [xabikos/vscode-javascript#26]
Hello ! 
        I am glad to use your extension,but can it support .vue file?   Thank you .

**Comment by afontcu** [comment]
+1!

**Comment by xabikos** [comment]
Closed by #29

**Comment by stevgouws** [comment]
Hi, do I need to change any settings or anything to get it to work in .vue files? Works in .js but doesn't give snippets in .vue.

**Comment by xabikos** [comment]
No you shouldn't change anything. I tested in my set up and it works, as long as VS Code recognizes the file as the correct language `vue`
