### ISSUE TITLE
Separate ES6 from non-ES6 snippets

### ISSUE THREAD

**Issue by whitlockjc** [xabikos/vscode-javascript#3]
What do you think about breaking these snippets up into logical groups so that people that want the `console.*` stuff can get it without having to only support ES6 snippets for the others?  Right now, your snippets are a mix of ES6 snippets and non-ES6 _(`console.*`, class properties, ...)_ snippets.  The idea would be to have ES5 snippets, ES6 snippets and common snippets that are not tied to a specific JavaScript language version.  Then people could choose things based on their environment without being forced one way or another.  I'd love to help if you agree.

**Comment by xabikos** [comment]
Sorry for my late reply. I was thinking of that approach but finally didn't go this path as would require to publish and maintain multiple versions of common functionality. Personally I am only using ES6 syntax and through this extension I wanted to point to this direction as everyone sooner or later has to go there. Whoever feels there is a need to create an extension like that can publish it.
