### ISSUE TITLE
how to find it in VScode marketplace?

### ISSUE THREAD

**Issue by xgqfrms-gildata** [xabikos/vscode-javascript#31]
https://marketplace.visualstudio.com/items?itemName=xabikos.vscode-javascript

**Comment by xgqfrms-gildata** [comment]
![image](https://user-images.githubusercontent.com/29531779/30628972-00401b7a-9e0c-11e7-9992-d41d9b48b3c9.png)

**Comment by xgqfrms-gildata** [comment]
https://marketplace.visualstudio.com/items?itemName=xabikos.vscode-react

**Comment by xabikos** [comment]
Hello @xgqfrms-gildata 

I am not sure what is the problem here so I will close the issue.. 

Feel free to open it again if you need any help.

**Comment by xgqfrms-gildata** [comment]
404 ???
