### ISSUE TITLE
Doesn't work in visual studio insiders version

### ISSUE THREAD

**Issue by etiennejcharles** [xabikos/vscode-javascript#39]
Thanks for such a great extension! 

When I download the extension, and activate it in Visual Studio Code Insiders, it doesn't work, 
Would you have an idea why ? 

It does work in the "normal" version of vscode though

Thanks in advance!

**Comment by xabikos** [comment]
@etiennejcharles my apologies for the really late reply. 

Is this still an issue? I have never test the extension with insiders version.

**Comment by xabikos** [comment]
I am closing this as no further info was provided.
@etiennejcharles  feel free to open it again if you would like to add some more info.
