### ISSUE TITLE
add a snippet for Import and export

### ISSUE THREAD

**Issue by ZSkycat** [xabikos/vscode-javascript#48]
`export {  } from './module'`

**Comment by xabikos** [comment]
@ZSkycat could you give some more info on how this should behave because I am confused.

The intent is to export something we importing from another module?

**Comment by ZSkycat** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export

**Comment by ZSkycat** [comment]
I created my own code snippet extension.
https://github.com/ZSkycat/vscode-javascript-snippets-of-cat
