### ISSUE TITLE
Unknown language 'vue' in `contributes.JavaScriptSnippets.language`

### ISSUE THREAD

**Issue by GoGoris** [xabikos/vscode-javascript#49]
The following error is logged in VS Code. I cannot find this setting, is this an internal setting inside the plugin?

%USERPROFILE%\.vscode\extensions\xabikos.javascriptsnippets-1.6.0]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue

**Comment by xabikos** [comment]
@GoGoris thanks for reporting this. 

To make the snippets available in `Vue` language we need to specify the additional [option](https://github.com/xabikos/vscode-javascript/blob/master/package.json#L37) in `package.json` file. If you install the corresponding VS code [extension](https://marketplace.visualstudio.com/items?itemName=octref.vetur) that adds support for this language then the error is gone.

I close this, but feel free to open it again if you would like to provide more info.

**Comment by JustFly1984** [comment]
I'm not planning to use Vue, how do I disable this error without adding vue dependencies?

**Comment by usernamehw** [comment]
LMAO, that extension is one of the heaviest out there `150Mib` 👍 .

**Comment by JustFly1984** [comment]
I'm not using Vue too. How do I disable this error?

**Comment by JustAPhrog** [comment]
@xabikos Is it possible to disable error?

**Comment by credencie1** [comment]
@xabikos Any progress with this issue? I'm not using Vue and I'm not pretending to use it. How can I disable this error?

**Comment by JamesVexica** [comment]
Same not using vue and probably never will... please disabled or hide this error

**Comment by Bhavik47** [comment]
Has anyone solved this problem, javascript snippets are not working on my vscode, and this is the message in js extension;
Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue

**Comment by erfan-star-1999** [comment]
i have this problem too with JavaScript (ES6) code snippets extenstion, but its gone after install vetur. but why i should install this im not coding vue please fix your extension
