### ISSUE TITLE
fre-> results in wacky multiple text selections

### ISSUE THREAD

**Issue by nowherenearithaca** [xabikos/vscode-javascript#51]
Hi - just FYI - I started playing with this for "fre->" in latest VS Code and it seems to get selections in a all kind of wacky state - I type the first argument and then when I type the second, some text below it is also selected and gets modified.

**Comment by xabikos** [comment]
@nowherenearithaca could you give me an example when this happens? I tried to use the snippet and everything looks fine.

The contents of a test file would be great.

**Comment by xabikos** [comment]
I am closing this as no further info was provided. 
@nowherenearithaca feel free to open it again if you would like to add some more info.
