### ISSUE TITLE
Am I doing wrong or a bug?

### ISSUE THREAD

**Issue by minmur** [xabikos/vscode-javascript#52]
Hi.

Am I missing something or am using snippets somehow wrong, but behaviour at the moment looks fishy/buggy.

For example:
when using ``` ima->```, ```import { originalName as alias } from 'module';``` is inserted and thats ok. But highlighted part is ```module```. I can't "come back" to ```originalName``` and ```alias``` and change them fast as it should be when using snippets.

Hope, anyone understood what the problem is :)

**Comment by xabikos** [comment]
Hello @minmur 
I tested again the snippet you mentioned above (`ima`) and was able to navigate between the various variables. You should use the `tab` button to do so. 

I am closing this as I consider that everything works fine. But please feel free to open it again if you need further assistance.
