### ISSUE TITLE
clg snippet often results in 'class' instead of 'console.log'

### ISSUE THREAD

**Issue by Friksel** [xabikos/vscode-javascript#57]
I use the `clg` snippet a lot to `console.log`, but often when just typed exactly right this is not resulting in a `console.log()`, but in `class`. This is pretty frustrating, because it's happening a lot and if this shortcut results in wrong code it's missing the goal completely in saving time.

I'm not sure why this happens, because I definitely didn't made typos all those times this happened and wrote `clg` and didn't press tab (to confirm) after `cl` either. I always use tab to complete/confirm.
For some reason `class` and `console.log()` seem to be fighting under the hood to present themselves. Sometimes `console.log` wins, the other time `class` wins.

It also happens a lot that after typing `clg` and hitting TAB to complete the snippet nothing happens, so the snippet is not always working. Than I have to erase it, type `clg` again and again hit TAB. Mostly than it works (or get the `class` instead of `console.log` again).

So it's like something is conflicting with other snippets, but I don't use other es6/js snippet addons and don't have defined any custom snippets like this.

**Comment by Friksel** [comment]
It's 1,5 month ago since I posted this without reaction. This issue is happening a lot and I even see myself switching back to plain old console.log( typing instead to avoid this discomfort. Is this being picked up?

**Comment by rickhernandezio** [comment]
YES +1 to get this fixed!

**Comment by rickhernandezio** [comment]
So after playing around with this some more. 

I found the solution!

You have to update the quick suggestion delay time in your settings file.

`` "editor.quickSuggestionsDelay": 100``

**Comment by Friksel** [comment]
Thanks @rickhernandezio ! Great tip. I just set it to 100 msec and gonna try it out

**Comment by Friksel** [comment]
Just for future reference, didn't see `clg` result in `class` instead of `console.log()` again. So this seemed to have fixed it. Thanks @rickhernandezio
