### ISSUE TITLE
edf encourages bad code

### ISSUE THREAD

**Issue by dantman** [xabikos/vscode-javascript#62]
Documentation says that `edf` outputs `export default (parameter) => { console.log(parameter);};`.

This isn't a very good snippet since no-one should ever write code like this. `enf` is ok because anonymous/arrow functions get names from variable declarations. But an anonymous function does not get any name.

As a result the default exported function from this snippet will have no name in logs/debugging and will not be smart-imported by vscode.

`export default function ${1:${TM_FILENAME_BASE}}(parameter) { ...` would work better.

**Comment by xabikos** [comment]
Closed as implmented
