### ISSUE TITLE
TypeScript and JavaScript Language Features

### ISSUE THREAD

**Issue by marjel0412** [xabikos/vscode-javascript#69]
Issue Type: <b>Bug</b>

The TypeScript language service died 5 times right after it got started. The service will not be restarted.

Source: TypeScript and JavaScript Language Features (Extensio...)

Extension version: 1.7.2
VS Code version: Code 1.41.1 (26076a4de974ead31f97692a0d32f90d735645c0, 2019-12-18T14:58:56.166Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2400 CPU @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (3.18GB free)|
|Process Argv|D:\_PROGRAMIRANJE\_JavaScript, React, Native\___CUBES___\021 JS Funkcije - napredni deo\Domaci|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by xabikos** [comment]
@marjel0412  I don't see how this is relater to this extension. I am closing it but feel free to open it again if there is a need.
