### ISSUE TITLE
Error Unexpectedly

### ISSUE THREAD

**Issue by NarenderTyagi93** [xabikos/vscode-javascript#72]
Issue Type: <b>Bug</b>

Some error occured unexpectedly

Extension version: 1.7.2
VS Code version: Code 1.42.1 (c47d83b293181d9be64f27ff093689e8e7aed054, 2020-02-11T14:44:27.652Z)
OS version: Darwin x64 19.3.0

**Comment by xabikos** [comment]
@NarenderTyagi93 I don't see how this is relater to this extension. I am closing it but feel free to open it again if there is a need.
