### ISSUE TITLE
console.log is not active and working 

### ISSUE THREAD

**Issue by samiptimalsina** [xabikos/vscode-javascript#75]
Issue Type: <b>Feature Request</b>

console.log is not active and working 

Extension version: 1.8.0
VS Code version: Code 1.44.2 (ff915844119ce9485abfe8aa9076ec76b5300ddd, 2020-04-16T16:36:23.138Z)
OS version: Windows_NT x64 10.0.18363

**Comment by xabikos** [comment]
Thanks for reporting this @samiptimalsna 

But could you give some info about it? You mention about feature request. `clg` doesn't trigger `console.log`? And where do you see this error? 
I am using this in my day to day work and don't have any issue.
