### ISSUE TITLE
Typescript-Javascript extension error

### ISSUE THREAD

**Issue by josephozgen** [xabikos/vscode-javascript#76]
Issue Type: <b>Bug</b>

Process killed 5 times and gave error message about this.

Extension version: 1.8.0
VS Code version: Code - Insiders 1.45.0-insider (0778354f3a6a2c21b7f738a5e6b02e2f1c765e73, 2020-04-27T05:42:11.567Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (8.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by xabikos** [comment]
Thanks for creating this @josephozgen 

Could you give some more information please? I don't get the problem based on the provided details.

I am using the extension and be on version 1.45 without any issue

**Comment by josephozgen** [comment]
Done with that later on.

Thanks for the reply by the way.

Best.

Charalampos Karypidis <notifications@github.com>, 9 May 2020 Cmt, 07:23
tarihinde şunu yazdı:
