### ISSUE TITLE
Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue

### ISSUE THREAD

**Issue by SharakPL** [xabikos/vscode-javascript#78]
In WSL VSCode's dev tools console shows this error
> [xabikos.JavaScriptSnippets]: Unknown language in `contributes.JavaScriptSnippets.language`. Provided value: vue

It goes away if [Vetur](https://github.com/vuejs/vetur) is installed in WSL and enabled.
In Windows this doesn't seem to be a problem, even if Vetur is disabled.

Probably related to https://github.com/stylelint/vscode-stylelint/issues/106#issue-608384289

**Comment by xabikos** [comment]
Already discussed in #49 
There is no easy solution to this I am afraid. You either need to install `Vetur` as mentioned or I would need to remove the ability of having the snippets available for Vue files. 

I do understand that installing an extension that is not used is not the best solution, but I don't plan to remove Vue support for the snippets.

I am closing this but feel free to open it again if required.

**Comment by PoorCameraQuality** [comment]
Yeah This is just not ideal. I cannot get Javascript es6 code snippets to work because of this weird language issue. Tried installing all the other extentions listed in answers, still a problem. 

You should probably just remove it.

**Comment by SharakPL** [comment]
@PoorCameraQuality did you check console log? What's this **unknown language** you're missing?

**Comment by Bhavik47** [comment]
Has anyone solved this problem, javascript snippets are not working on my vscode, and this is the message in js extension;
Unknown language in contributes.JavaScriptSnippets.language. Provided value: vue
