### ISSUE TITLE
'afn' conflict with JavaScript Snippet Pack

### ISSUE THREAD

**Issue by gluons** [xabikos/vscode-javascript#9]
I'm using ES6 but I also use normal JavaScript snippet.

`afn` snippet of this extension conflict with [JavaScript Snippet Pack](https://marketplace.visualstudio.com/items?itemName=akamud.vscode-javascript-snippet-pack).

akamud/vscode-javascript-snippet-pack#2

**Comment by xabikos** [comment]
I change the trigger from `afn` to `anfn` and publish a new release. Hope this works better now

**Comment by gluons** [comment]
Thank you very much.
Now, I can use these together. 😃 
Closed.
